(async () => {
 'use strict';
 let backendReady=false; window.CATALOG=await DemoAPI('catalog');
 const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], C=CATALOG, O=OrderCore;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=n=>'Rs. '+n.toLocaleString('en-PK');
 const storage={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}};
 const paths={menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-8H9v8H4a1 1 0 0 1-1-1Z"/>',utensils:'<path d="M4 3v7a3 3 0 0 0 6 0V3M7 3v19M20 3c-4 2-5 7-5 10h5M20 3v19"/>',search:'<circle cx="10.5" cy="10.5" r="7.5"/><path d="m16 16 5 5"/>',flame:'<path d="M12 3c1 5 6 5 6 11a6 6 0 0 1-12 0c0-3 2-5 4-7 0 4 1 5 2 5s2-3 0-9Z"/>',pin:'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',bag:'<path d="m5 3-2 4v13a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1V7l-2-4ZM3 7h18M8 11a4 4 0 0 0 8 0"/>',phone:'<path d="m5 3 4 1 1 5-3 2a15 15 0 0 0 6 6l2-3 5 1 1 4c0 2-3 3-5 2C9 19 5 15 3 8 2 6 3 3 5 3Z"/>',headphones:'<path d="M3 14v-3a9 9 0 0 1 18 0v3M3 13h4v8H3Zm14 0h4v8h-4Z"/>',message:'<path d="M21 11a9 9 0 0 1-13 8l-5 2 2-5a9 9 0 1 1 16-5Z"/><path d="M8 10h8M8 14h5"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M5 5l1.5 1.5M17.5 17.5 19 19M5 19l1.5-1.5M17.5 6.5 19 5"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>','chevron-right':'<path d="m9 5 7 7-7 7"/>','chevron-left':'<path d="m15 5-7 7 7 7"/>','chevron-down':'<path d="m5 9 7 7 7-7"/>','arrow-left':'<path d="m12 4-8 8 8 8M4 12h17"/>',plus:'<path d="M5 12h14M12 5v14"/>',minus:'<path d="M5 12h14"/>',locate:'<circle cx="12" cy="12" r="7"/><circle cx="12" cy="12" r="2"/><path d="M12 1v4M12 19v4M1 12h4M19 12h4"/>',send:'<path d="m22 2-7 20-4-9-9-4ZM22 2 11 13"/>',cash:'<rect x="2" y="5" width="20" height="14" rx="2"/><circle cx="12" cy="12" r="3"/><path d="M5 12h1M18 12h1"/>',bike:'<circle cx="5" cy="17" r="4"/><circle cx="19" cy="17" r="4"/><circle cx="14" cy="4" r="2"/><path d="m9 17 3-6 3 6M8 10l4-3 4 4h4M12 7l-1 6H5"/>'};
 const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[n]||paths.bag}</svg>`;
 $$('[data-icon]').forEach(e=>e.innerHTML=icon(e.dataset.icon));
 let cart=storage.get('the-pizza-v2-cart',[]);if(!Array.isArray(cart))cart=[];cart=cart.filter(l=>O.valid(C,l)).slice(0,40);
 let fulfilment={type:'delivery',city:'',area:'',address:'',phone:'',coords:null},draft={...fulfilment}, selected=null,sizeId='',choices={},quantity=1,toastTimer,map,marker,checkoutPending=false;
 function closeAll(){$$('dialog[open]').forEach(d=>d.close())}
 function open(id){closeAll();$(id).showModal()}
 $$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
 $$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}));
 function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2800)}
 function applyTheme(t){document.documentElement.dataset.theme=t;storage.set('the-pizza-theme',t);$$('.theme-toggle').forEach(b=>b.setAttribute('aria-label',`Switch to ${t==='dark'?'light':'dark'} mode`));$('#theme-name').textContent=t==='dark'?'Dark Mode':'Light Mode';$('#theme-status').textContent='ENABLED'}
 applyTheme(storage.get('the-pizza-theme','dark')==='light'?'light':'dark');$$('.theme-toggle').forEach(b=>b.onclick=()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));
 $('#year').textContent=new Date().getFullYear();
 function saveCart(){storage.set('the-pizza-v2-cart',cart);const count=cart.reduce((a,l)=>a+l.qty,0);$$('.cart-count').forEach(e=>{e.textContent=count;e.hidden=!count})}
 function navigateCategory(id){closeAll();const el=$('#category-'+id);el?.scrollIntoView({block:'start'});$$('.categories button').forEach(b=>b.classList.toggle('active',b.dataset.category===id))}
 function action(name){switch(name){case'sidebar':open('#sidebar');break;case'home':closeAll();window.scrollTo({top:0});$('.categories button').forEach((b,i)=>b.classList.toggle('active',i===0));$('#categories').scrollTo({left:0});break;case'menu':navigateCategory(C.categories[0].id);break;case'deals':navigateCategory('4');break;case'search':open('#search-dialog');$('#search').focus();renderSearch();break;case'location':checkoutPending=false;open('#service-dialog');break;case'cart':renderCart();open('#cart-dialog');break;case'support':info('SUPPORT & CONTACT',`<p>For delivery, pickup, order updates or help choosing your favourites, contact the shop.</p><a class="primary full" href="tel:${SHOP.phone}">${icon('phone')}0335-3856228</a><a class="primary full" href="https://wa.me/${SHOP.whatsapp}" target="_blank" rel="noopener">${icon('message')}CHAT ON WHATSAPP</a>`);break;case'feedback':info('SHARE FEEDBACK',`<p>Tell us about your food and ordering experience directly on WhatsApp.</p><a class="primary full" href="https://wa.me/${SHOP.whatsapp}?text=${encodeURIComponent('Hello the pizza, I would like to share feedback:')}" target="_blank" rel="noopener">${icon('message')}SHARE ON WHATSAPP</a>`);break;case'privacy':info('PRIVACY & ORDERING','<p>This demo stores menu changes and order details in this browser. Checkout opens WhatsApp with your items, contact details and delivery address or pickup information. Tap Send in WhatsApp to send the order to the shop. There is no shared online order database.</p><p>Location detection requires browser permission and HTTPS or localhost. The map uses OpenStreetMap tiles. Manual address entry works without location permission. Orders are confirmed only when the shop replies. Payment is cash only.</p>');}}
 function info(title,body){$('#info-title').textContent=title;$('#info-content').innerHTML=body;open('#info-dialog')}
 $$('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));
 $('#categories').innerHTML=C.categories.map((c,i)=>`<button data-category="${c.id}" class="${i?'':'active'}">${esc(c.label)}</button>`).join('');
 $$('#categories button').forEach(b=>b.onclick=()=>navigateCategory(b.dataset.category));
 function card(p){const old=Number(p.originalPrice),price=p.basePrice;return `<article class="product-card" tabindex="0" role="button" aria-label="Customise ${esc(p.name)}" data-product="${p.id}"><div class="product-image"><img src="${p.image}" alt="${esc(p.name)}" loading="lazy" width="384" height="384">${old>price?`<span class="save-tag">SAVE ${Math.round((old-price)/old*100)}%</span>`:''}</div><div class="card-body"><h3>${esc(p.name)}</h3>${p.description?`<p>${esc(p.description)}</p>`:''}<div class="card-bottom"><div class="price">${old>price?`<del>Rs. ${old}</del>`:''}${price>0?`<small>Rs.</small>${price}`:'<small>Choose option</small>'}</div><span class="plus" aria-hidden="true">${icon('plus')}</span></div></div></article>`}
 $('#catalog').innerHTML=C.categories.map(c=>{const ps=C.products.filter(p=>p.category===c.id);return `<section class="menu-section" id="category-${c.id}"><div class="section-head"><h2>${esc(c.label)}</h2>${c.id==='6'?'<span class="countdown">MIDNIGHT SPECIALS</span>':''}<span>${ps.length} Items</span><button data-category-all="${c.id}">ALL ${icon('chevron-right')}</button></div><div class="product-grid">${ps.map(card).join('')}</div></section>`}).join('');
 $$('.product-card').forEach(el=>{el.onclick=()=>showProduct(el.dataset.product);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showProduct(el.dataset.product)}}});
 $$('[data-category-all]').forEach(b=>b.onclick=()=>{open('#search-dialog');$('#search').value=C.categories.find(c=>c.id===b.dataset.categoryAll).label;renderSearch()});
 if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){$$('.categories button').forEach(b=>b.classList.toggle('active','category-'+b.dataset.category===e.target.id));const active=$('.categories .active');if(active)$('#categories').scrollTo({left:active.offsetLeft-32,behavior:'smooth'})}},{rootMargin:'-190px 0px -55% 0px'});$$('.menu-section').forEach(e=>observer.observe(e))}
 let banner=0;function renderBanner(){const b=SHOP.banners[banner];$('#banner-image').src=b.image;$('#banner-image').alt=b.alt;$('#banner-dots').innerHTML=SHOP.banners.map((_,i)=>`<button class="${i===banner?'active':''}" aria-label="Show banner ${i+1}" aria-pressed="${i===banner}" data-slide="${i}"></button>`).join('');$$('[data-slide]').forEach(b=>b.onclick=()=>{banner=Number(b.dataset.slide);renderBanner()})}
 $('#banner-prev').onclick=()=>{banner=(banner-1+SHOP.banners.length)%SHOP.banners.length;renderBanner()};$('#banner-next').onclick=()=>{banner=(banner+1)%SHOP.banners.length;renderBanner()};$('#banner-product').onclick=()=>{const b=SHOP.banners[banner],p=C.products.find(p=>p.name===b.product);p?showProduct(p.id):navigateCategory(b.category||'4')};renderBanner();
 if(!matchMedia('(prefers-reduced-motion: reduce)').matches)setInterval(()=>{if(document.hidden||$('dialog[open]')||$('.banner:hover')||$('.banner:focus-within'))return;banner=(banner+1)%SHOP.banners.length;renderBanner()},6500);
 function renderSearch(){const q=$('#search').value.trim().toLowerCase(),ps=C.products.filter(p=>(p.name+' '+p.description+' '+p.categoryName).toLowerCase().includes(q));$('#search-results').innerHTML=ps.length?ps.map(p=>`<button class="search-result" data-result="${p.id}"><img src="${p.image}" alt="" loading="lazy"><span><strong>${esc(p.name)}</strong><small>${p.basePrice?money(p.basePrice):'Choose your drink'}</small></span>${icon('plus')}</button>`).join(''):'<div class="empty">No products found. Try pizza, wings or pasta.</div>';$$('[data-result]').forEach(b=>b.onclick=()=>showProduct(b.dataset.result))}$('#search').oninput=renderSearch;
 function selectedSize(){return selected.sizes.find(s=>s.id===sizeId)}
 function resetChoices(){choices={};for(const g of selectedSize().groups)if(g.options.length===1&&g.min>0)choices[g.id]=[g.options[0].id]}
 function line(){return {id:selected.id,size:sizeId,options:choices,qty:quantity}}
 function showProduct(id){selected=C.products.find(p=>p.id===id);sizeId=selected.sizes[0].id;quantity=1;resetChoices();$('#product-content').innerHTML=`<div class="product-layout"><div class="product-visual"><img src="${selected.popupImage||selected.image}" alt="${esc(selected.name)}"></div><div class="product-details"><div class="product-details-top"><h2>${esc(selected.name)}</h2>${selected.description?`<p class="product-description">${esc(selected.description)}</p>`:''}<div class="product-base-price" id="product-price"></div></div><form id="product-form"><div class="product-options"><div id="sizes"></div><div id="option-groups"></div></div><div class="product-bottom"><p id="product-error" class="error" role="alert"></p><div class="product-actions"><div class="quantity"><button type="button" id="minus" aria-label="Decrease quantity">${icon('minus')}</button><span id="qty">1</span><button type="button" id="plus" aria-label="Increase quantity">${icon('plus')}</button></div><button type="submit" class="primary" id="add-cart"></button></div></div></form></div></div>`;renderSizes();renderOptions();$('#minus').onclick=()=>{quantity=Math.max(1,quantity-1);updateProductPrice()};$('#plus').onclick=()=>{quantity=Math.min(20,quantity+1);updateProductPrice()};$('#product-form').onsubmit=addToCart;updateProductPrice();open('#product-dialog')}
 function renderSizes(){const ss=selected.sizes;$('#sizes').innerHTML=ss.length>1?`<fieldset><legend>Choose Your Size<small>Required · Select one</small></legend><div class="option-grid size-grid">${ss.map(s=>`<label class="option-tile"><input type="radio" name="size" aria-label="${esc(s.name)}" value="${s.id}" ${s.id===sizeId?'checked':''}><span>${s.image?`<img src="${s.image}" alt="" loading="lazy">`:''}<b>${esc(s.name)}</b><small>${money(s.price)}</small></span></label>`).join('')}</div></fieldset>`:'';$$('#sizes input').forEach(i=>i.onchange=()=>{sizeId=i.value;resetChoices();renderOptions();updateProductPrice()})}
 function renderOptions(){$('#option-groups').innerHTML=selectedSize().groups.map(g=>`<fieldset class="option-group" data-group="${g.id}"><legend>${esc(g.name)}<small>${g.min?'Required':'Optional'} · ${g.max===1?'Select one':'Choose your extras'}</small></legend><div class="option-grid">${g.options.map(o=>`<label class="option-tile"><input type="${g.max===1?'radio':'checkbox'}" name="group-${g.id}" aria-label="${esc(o.name)}" value="${o.id}" ${(choices[g.id]||[]).includes(o.id)?'checked':''}><span>${o.image?`<img src="${o.image}" alt="" loading="lazy">`:''}<b>${esc(o.name)}</b><small>${o.price?'+ '+money(o.price):'Included'}</small></span></label>`).join('')}</div></fieldset>`).join('');$$('#option-groups input').forEach(i=>i.onchange=()=>{const group=i.closest('[data-group]'),id=group.dataset.group;choices[id]=[...group.querySelectorAll('input:checked')].map(x=>x.value);group.classList.remove('invalid');$('#product-error').textContent='';updateProductPrice()})}
 function updateProductPrice(){const price=O.unit(C,line());$('#product-price').innerHTML=`<small>Rs.</small> ${price.toLocaleString()}`;$('#qty').textContent=quantity;$('#minus').disabled=quantity===1;$('#plus').disabled=quantity===20;$('#add-cart').innerHTML=`<span>ADD TO CART</span><span>${money(price*quantity)}</span>`}
 function addToCart(e){e.preventDefault();const missing=selectedSize().groups.find(g=>(choices[g.id]||[]).length<g.min);if(missing){$('#product-error').textContent='Please complete: '+missing.name;const el=$(`[data-group="${missing.id}"]`);el.classList.add('invalid');el.scrollIntoView({block:'center',behavior:'smooth'});return}const next=JSON.parse(JSON.stringify(line()));if(!O.valid(C,next)){toast('Please review your product choices.');return}const key=l=>JSON.stringify([l.id,l.size,Object.entries(l.options).sort().map(([k,v])=>[k,[...v].sort()])]);const same=cart.find(l=>key(l)===key(next));if(same&&same.qty+next.qty>20){toast('Maximum 20 of the same item per order');return}if(!same&&cart.length>=40){toast('Your cart is full. Please checkout first.');return}same?same.qty+=next.qty:cart.push(next);saveCart();$('#product-dialog').close();toast(selected.name+' added to your cart')}
 function summary(){const sub=O.subtotal(C,cart),fee=fulfilment.type==='pickup'?0:SHOP.deliveryFee;return `<div class="summary"><div><span>Subtotal</span><span>${money(sub)}</span></div><div><span>${fulfilment.type==='pickup'?'Pickup':'Delivery fee'}</span><span>${money(fee)}</span></div><div class="total"><span>Total</span><span>${money(sub+fee)}</span></div></div>`}
 function renderCart(){if(!cart.length){$('#cart-content').innerHTML=`<div class="empty">${icon('bag')}<h3>Your cart is empty</h3><p>Add something delicious from our menu.</p><button class="primary full" id="browse">BROWSE MENU</button></div>`;$('#browse').onclick=()=>action('menu');return}$('#cart-content').innerHTML=cart.map((l,i)=>{const p=O.find(C,l).product;return `<div class="cart-line"><img src="${p.image}" alt="${esc(p.name)}"><div class="cart-line-info"><h3>${esc(p.name)}</h3><p>${esc(O.details(C,l)||'Regular')}</p><div class="quantity"><button data-change="${i}" data-delta="-1" aria-label="Decrease ${esc(p.name)}">−</button><span>${l.qty}</span><button data-change="${i}" data-delta="1" aria-label="Increase ${esc(p.name)}" ${l.qty===20?'disabled':''}>+</button></div></div><div class="line-price">${money(O.unit(C,l)*l.qty)}<button class="remove" data-remove="${i}" aria-label="Remove ${esc(p.name)}">Remove</button></div></div>`}).join('')+summary()+`<button class="primary full" id="checkout">CHECKOUT ${icon('chevron-right')}</button><p class="privacy-hint">${fulfilment.type==='pickup'?'Cash on pickup':'Cash on delivery'} · No sign-in needed</p>`;$$('[data-change]').forEach(b=>b.onclick=()=>{const i=+b.dataset.change;cart[i].qty+=+b.dataset.delta;if(cart[i].qty<=0)cart.splice(i,1);saveCart();renderCart()});$$('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.remove,1);saveCart();renderCart()});$('#checkout').onclick=openCheckout}
 function openCheckout(){if(!cart.length)return;const pickup=fulfilment.type==='pickup';$('#checkout-service-label').textContent=pickup?'Pickup · '+SHOP.pickupName:'Delivery';$('#delivery-fields').hidden=pickup;$('#checkout-pickup').hidden=!pickup;$('#checkout-pickup').textContent=SHOP.pickupAddress;$('#payment-label').textContent=pickup?'Cash on pickup':'Cash on delivery';const f=$('#checkout-form');f.elements.area.required=!pickup;f.elements.address.required=!pickup;f.elements.phone.value=fulfilment.phone||f.elements.phone.value;f.elements.area.value=[fulfilment.city,fulfilment.area].filter(Boolean).join(', ')||f.elements.area.value;f.elements.address.value=fulfilment.address||f.elements.address.value;$('#checkout-summary').innerHTML=summary();$('#checkout-error').textContent='';open('#checkout-dialog')}
 $('#change-service').onclick=()=>{checkoutPending=true;open('#service-dialog')};
 $('#checkout-form').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));Object.keys(d).forEach(k=>d[k]=d[k].trim());if(d.name.length<2||!O.phone(d.phone)){$('#checkout-error').textContent='Enter your name and a valid mobile number.';return}if(fulfilment.type==='delivery'&&(d.area.length<2||d.address.length<8)){$('#checkout-error').textContent='Enter your area and complete address.';return}try{if(!cart.length||!cart.every(l=>O.valid(C,l)))throw Error('Review your cart and required options.');const result=await DemoAPI('orders','POST',{key:crypto.randomUUID(),lines:cart,customer:d,fulfilment,source:'web',expectedTotal:O.subtotal(C,cart)+(fulfilment.type==='delivery'?SHOP.deliveryFee:0)});const whatsappURL=O.url(SHOP,O.message(C,cart,SHOP,d,fulfilment,result.id));cart=[];saveCart();window.location.assign(whatsappURL)}catch(err){$('#checkout-error').textContent=err.message}};
 function updateLocationLabel(){$('#service-label').textContent=fulfilment.type==='pickup'?'PICKUP FROM':'DELIVERING TO';$('#location-label').textContent=fulfilment.type==='pickup'?SHOP.pickupName:fulfilment.area||'Select location'}
 function showManual(){$('#manual-fields').hidden=false;$('#location-form').elements.city.disabled=false;$('#location-form').elements.area.disabled=false}
 function initMap(){if(!window.L){$('#map-status').textContent='Map unavailable. Please enter your address manually.';return}if(!map){map=L.map('map',{zoomControl:false}).setView(SHOP.mapCenter,SHOP.mapZoom);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',maxZoom:19}).addTo(map).on('tileerror',()=>{$('#map-status').textContent='Map tiles unavailable. You can still enter your address manually.'});map.on('click',e=>{if(draft.type==='delivery'){setPin(e.latlng.lat,e.latlng.lng);showManual()}})}requestAnimationFrame(()=>map.invalidateSize());if(draft.coords)setPin(...draft.coords);else if(marker){marker.remove();marker=null}}
 function setPin(lat,lng){draft.coords=[Number(lat.toFixed(6)),Number(lng.toFixed(6))];if(map){if(marker)marker.setLatLng(draft.coords);else marker=L.marker(draft.coords,{icon:L.divIcon({className:'map-pin',iconSize:[24,24],iconAnchor:[12,12]})}).addTo(map);map.setView(draft.coords,15)}$('#map-status').textContent='Map pin selected. Add your area and street address to complete delivery details.'}
 function openLocation(type){draft={...fulfilment,type,coords:fulfilment.coords?[...fulfilment.coords]:null};const pickup=type==='pickup',f=$('#location-form');$('#location-service').innerHTML=icon(pickup?'bag':'bike')+(pickup?'Pickup':'Delivery');$('#pickup-info').hidden=!pickup;$('#pickup-name').textContent=SHOP.pickupName;$('#pickup-address').textContent=SHOP.pickupAddress;$('#manual-fields').hidden=pickup||!draft.area;f.elements.city.disabled=pickup||!draft.area;f.elements.area.disabled=pickup||!draft.area;$('#location-address-label').hidden=pickup;f.elements.city.value=draft.city;f.elements.area.value=draft.area;f.elements.address.value=draft.address;f.elements.phone.value=draft.phone;$('#detect-location').hidden=pickup;$('#manual-location').hidden=pickup;$('#map-detect').hidden=pickup;$('#location-error').textContent='';$('#map-status').textContent=pickup?'Call the shop to confirm your pickup address.':'Choose a map pin or enter your address manually.';open('#location-dialog');initMap()}
 $$('[data-service]').forEach(b=>b.onclick=()=>openLocation(b.dataset.service));$('#location-back').onclick=()=>open('#service-dialog');$('#manual-location').onclick=()=>{draft.coords=null;if(marker){marker.remove();marker=null}showManual();$('#map-status').textContent='Enter your city, area and address manually.';$('#location-form').elements.city.focus()};
 function detect(){if(!navigator.geolocation){$('#location-error').textContent='Location detection is unavailable. Enter your address manually.';showManual();return}$('#detect-location').disabled=true;$('#detect-location').innerHTML=icon('locate')+'Locating…';$('#location-error').textContent='';navigator.geolocation.getCurrentPosition(pos=>{setPin(pos.coords.latitude,pos.coords.longitude);showManual();restoreDetect();$('#location-form').elements.city.focus()},err=>{restoreDetect();showManual();$('#location-error').textContent=err.code===1?'Location permission was denied. Please enter your address manually.':'Could not find your location. Please enter your address manually.'},{enableHighAccuracy:true,timeout:12000,maximumAge:60000})}
 function restoreDetect(){$('#detect-location').disabled=false;$('#detect-location').innerHTML=icon('locate')+'Detect My Location'}$('#detect-location').onclick=detect;$('#map-detect').onclick=detect;
 $('#location-form').onsubmit=e=>{e.preventDefault();const f=e.target,d={city:f.elements.city.value.trim(),area:f.elements.area.value.trim(),address:f.elements.address.value.trim(),phone:f.elements.phone.value.trim()};if(!O.phone(d.phone)){$('#location-error').textContent='Enter a valid Pakistani mobile number.';return}if(draft.type==='delivery'&&(d.city.length<2||d.area.length<2)){showManual();$('#location-error').textContent='Enter your city and area to save your location.';return}fulfilment={...draft,...d};updateLocationLabel();$('#location-dialog').close();toast(draft.type==='pickup'?'Pickup selected':'Delivery location saved');if(checkoutPending){checkoutPending=false;openCheckout()}};
 // Read-only optional browser-agent integration. It never sends an order.
 if(navigator.modelContext?.registerTool)try{navigator.modelContext.registerTool({name:'view_menu',description:'Read the pizza menu, options and current cart.',inputSchema:{type:'object',properties:{}},execute:async()=>({content:[{type:'text',text:JSON.stringify({catalog:C,cart,deliveryFee:SHOP.deliveryFee})}]})})}catch{}
 function updateCountdown(){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Karachi',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date());const read=t=>Number(parts.find(p=>p.type===t).value);const now=read('hour')*3600+read('minute')*60+read('second');const active=now<18000||now>=86100;const seconds=active?(18000-now+86400)%86400:86100-now;const clock=[Math.floor(seconds/3600),Math.floor(seconds%3600/60),seconds%60].map(n=>String(n).padStart(2,'0')).join(':');const el=$('.countdown');if(el)el.textContent=(active?'CLOSES IN ':'OPENS IN ')+clock;}updateCountdown();setInterval(updateCountdown,1000);saveCart();if(SHOP.showServiceOnStart)open('#service-dialog');
})();
