/* Deliberately public, browser-only demonstration. No credentials or remote database. */
(()=>{const key='the-pizza-static-demo-v1',clone=x=>JSON.parse(JSON.stringify(x));let memory;
function seed(){const catalog=clone(window.CATALOG),now=Date.now(),orders=[];const statuses=['pending','confirmed','preparing','out-for-delivery','delivered','returned','cancelled'];for(let i=0;i<24;i++){const p=catalog.products[i%catalog.products.length],s=p.sizes[0],status=i<7?statuses[i]:'delivered',at=new Date(now-i*2*86400000).toISOString();orders.push({id:'DEMO-'+String(i+1).padStart(4,'0'),key:'seed-'+i,source:i%3?'web':'pos',status,createdAt:at,updatedAt:at,completedAt:['delivered','returned'].includes(status)?at:null,customer:{name:'Sample customer '+(i+1),phone:'',address:'Sample address — not a real order',area:'Demo area'},fulfilment:{type:'pickup'},lines:[{name:p.name,productId:p.id,details:'Sample item',qty:1,unit:s.price}],subtotal:s.price,fee:0,total:s.price,history:[{status,at}]})}return {catalog,orders,revision:1,shop:clone(window.SHOP)}}
function read(){if(memory)return clone(memory);try{const saved=localStorage.getItem(key);memory=saved?JSON.parse(saved):seed()}catch{memory=seed()}return clone(memory)}
function save(value){try{localStorage.setItem(key,JSON.stringify(value))}catch{throw Error('Browser storage is full or unavailable. Use smaller images, download a backup, then reset the demo if needed.')}memory=clone(value)}
window.addEventListener('storage',e=>{if(e.key===key)memory=null});
window.DemoAPI=async(url,method='GET',b={})=>{const db=read();if(url==='login'||url==='logout')return {ok:true};if(url==='admin/state')return db;if(url==='catalog')return {...db.catalog,products:db.catalog.products.filter(p=>p.isActive!==false)};if(url==='reset'){save(seed());return {ok:true}};
if(url==='admin/catalog'){if(b.revision!==db.revision)throw Error('The demo menu changed in another tab. Refresh first.');const c=b.catalog;if(!c.categories.length)throw Error('Keep at least one category.');for(const p of c.products){if(!p.name.trim()||!c.categories.some(c=>c.id===p.category)||!p.sizes.length)throw Error('Check product names, categories and sizes.');for(const s of p.sizes){if(!s.name.trim()||!Number.isFinite(s.price)||s.price<0)throw Error('Enter a valid size and price.');for(const g of s.groups){if(!g.name.trim()||!g.options.length||!Number.isInteger(g.min)||!Number.isInteger(g.max)||g.min<0||g.max<g.min||g.min>g.options.length||g.options.some(o=>!o.name.trim()||!Number.isFinite(o.price)||o.price<0))throw Error('Check option names, prices and choice limits.')}}}db.catalog=clone(c);db.revision++;save(db);return {revision:db.revision}}
if(url==='admin/image'){if(!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(b.data||''))throw Error('Choose PNG, JPEG or WebP');if(b.data.length>680000)throw Error('Demo images must be under 500 KB.');return {url:b.data}}
if(url==='orders'){const old=db.orders.find(o=>o.key===b.key);if(old)return {id:old.id,total:old.total};if(!Array.isArray(b.lines)||!b.lines.length||!b.lines.every(l=>OrderCore.valid(db.catalog,l)&&OrderCore.find(db.catalog,l).product.isActive!==false))throw Error('Review your products and required options.');const lines=b.lines.map(l=>({name:OrderCore.find(db.catalog,l).product.name,productId:l.id,details:OrderCore.details(db.catalog,l),qty:l.qty,unit:OrderCore.unit(db.catalog,l)})),subtotal=lines.reduce((n,l)=>n+l.qty*l.unit,0),fee=b.fulfilment.type==='delivery'?db.shop.deliveryFee:0,total=subtotal+fee,pos=b.source==='pos';if(b.expectedTotal!==undefined&&b.expectedTotal!==total)throw Error('Demo prices changed. Refresh the menu.');if(pos&&(!Number.isFinite(b.cash)||b.cash<total))throw Error('Enter enough cash to cover the bill.');const at=new Date().toISOString(),status=pos?'delivered':'pending',o={id:'DEMO-'+crypto.randomUUID().slice(0,8).toUpperCase(),key:b.key,source:pos?'pos':'web',status,createdAt:at,updatedAt:at,completedAt:pos?at:null,customer:b.customer,fulfilment:b.fulfilment,lines,subtotal,fee,total,cashReceived:pos?b.cash:null,change:pos?b.cash-total:null,history:[{status,at}]};db.orders.unshift(o);save(db);return {id:o.id,total}}
if(url==='admin/order'){const o=db.orders.find(o=>o.id===b.id),allowed={pending:['confirmed','cancelled'],confirmed:['preparing','cancelled'],preparing:['out-for-delivery','delivered','cancelled'],'out-for-delivery':['delivered','returned'],delivered:['returned'],returned:[],cancelled:[]};if(!o||!allowed[o.status].includes(b.status))throw Error('Invalid status change.');o.status=b.status;o.updatedAt=new Date().toISOString();if(b.status==='delivered')o.completedAt=o.updatedAt;o.history.push({status:b.status,at:o.updatedAt});save(db);return o}throw Error('Not available in this static demo.');};
})();
